In [1]:
import numpy as np

In [ ]:
mylist= [10,20,30,'Apple', True, 8.20]
print(type(mylist))

<class 'list'>


In [ ]:
mylist.extend([30,40])
mylist
# using mylist.append() will create a list in list

[10, 20, 30, 'Apple', True, 8.2, 30, 40]

In [ ]:
mylist.reverse

print(mylist.reverse)
# .reverse() do not work because 

<built-in method reverse of list object at 0x7ff544a015f0>


In [ ]:
reversed_list= mylist[::-1]
print(reversed_list)
# in mylist[::-1] first : indicates a start value, second : indicates end value and -1 indicates reverse 

[40, 30, 8.2, True, 'Apple', 30, 20, 10]


In [ ]:
diction= {1 :'data', 2: 'information', 3:'text'}
print(type(diction))
print(diction)

# to create the dictionary

<class 'dict'>
{1: 'data', 2: 'information', 3: 'text'}


In [ ]:
diction.pop(3)
diction
# to remove the element

'text'

In [ ]:
diction.update({4: 'features'})
diction
# first method to add key and value

{1: 'data', 2: 'information', 4: 'features'}

In [ ]:
diction[5]= 'Rohit'
diction
# second method to add key and value

{1: 'data', 2: 'information', 4: 'features', 5: 'Rohit'}

In [ ]:
diction[1]
# to fetch the first element

'data'

In [ ]:
my_tuple= (1,2,3,'apple','Mango')
print(type(my_tuple))
print(my_tuple)

<class 'tuple'>
(1, 2, 3, 'apple', 'Mango')


In [ ]:
tup1=(1,2,3)
tup2=('apple', 'mango')

In [ ]:
my_tuple2=tup1+ tup2
print(type(my_tuple2))
print(my_tuple2)

<class 'tuple'>
(1, 2, 3, 'apple', 'mango')


In [ ]:
numeric_tuple= (10,20,30,40,50,60)
print(type(numeric_tuple))
print(numeric_tuple)

<class 'tuple'>
(10, 20, 30, 40, 50, 60)


In [ ]:
min(numeric_tuple)
# to get min vlaue

10

In [ ]:
np.min(numeric_tuple)

10

In [ ]:
r1= np.concatenate((my_tuple, numeric_tuple), axis= 0)
r1
# concatenate = add

array(['1', '2', '3', 'apple', 'Mango', '10', '20', '30', '40', '50',
       '60'], dtype='<U21')

In [ ]:
newdupli= my_tuple*2
newdupli
# duplicate the tuples

(1, 2, 3, 'apple', 'Mango', 1, 2, 3, 'apple', 'Mango')

In [ ]:
set1= {1,2,3,4,5}
set2= {2,3,7,6,1}
print(type(set1))
# create set

<class 'set'>


In [ ]:
# union of set1 and set2
# union will take "unique values"
print(set1.union(set2))

{1, 2, 3, 4, 5, 6, 7}


In [ ]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
print(set1.intersection(set2))

{1, 2, 3}


In [ ]:
# intersection of set1 and set2
# intersection takes "only common values" between two sets
set1.intersection(set2)

{1, 2, 3}

In [ ]:
# to get difference
print(set1-set2)

{4, 5}


In [ ]:
set1.difference(set2)

{4, 5}

In [ ]:
# Create matrix
mat= np.arange(2,11).reshape(3,3)
mat

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
y=[]
a= int(input('size of array: '))
for i in range(a):
  x= int(input('Element'))
  y.append(x)
c= np.array(y)
print('original array is: ', c)

z= np.array(c, dtype= float)
print('converted array is: ', z)

size of array: 4
Element1
Element2
Element3
Element4
original array is:  [1 2 3 4]
converted array is:  [1. 2. 3. 4.]


In [ ]:
arr1= np.array([10,20,30])
arr1


array([10, 20, 30])

In [ ]:
arr1= np.append(arr1,[[40,50,60,70,80,90]])
print(arr1)

[10 20 30 40 50 60 70 80 90]


In [ ]:
a= np.array([10,20,30])
b= np.array([40,50,60,70,80,90])
np.append(a,b)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x= np.array([10,20,30])
y= np.array([40,50,60])
sumArray= np.add(x,y)
print(sumArray)
# to add np.array

[50 70 90]


In [ ]:
print(x+y)

[50 70 90]


# solved

In [12]:
a= np.arange(1,10)
array1= np.reshape(a,(3,3))
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# case study Numpy 

In [ ]:
a= np.full((3,3), 5)
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
def tup():
  y=[]
  for i in range(2):
    y.append(int(input()))
  a= tuple(y)
  b= np.full(a,5)
  return b
tup()

3
3


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
def arr(m,n):
  return(np.full(m,n))
print(arr([3,3],5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
def add1(c,d):
  f= np.add(c,d)
  return f
c= np.array ([1,2,3])
d= np.array ([4,5,6])

add1(c,d)

array([5, 7, 9])

In [ ]:
matrix= np.array([1,2,3,4,5,6,7,8,9])
x= matrix.reshape(3,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
def top_left(matrix,a,b):
  print(matrix[:a,:b])

In [ ]:
top_left(x, 2,2)

[[1 2]
 [4 5]]


In [ ]:
def bottom_right(matrix,a,b):
  print(matrix[a:,b:])
bottom_right(x,1,1)

[[5 6]
 [8 9]]


In [ ]:
def compute(k):
  m= np.mean(k)
  n= np.std(k)
  dict1= {'mean': m, 'std': n}
  return dict1

In [ ]:
k= np.array ([1,1,1])
compute(k)

{'mean': 1.0, 'std': 0.0}