In [1]:
import numpy as np

In [2]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr=np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr1= np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2= arr.ravel()
arr2

array([1, 2, 3, 4, 5, 6])

In [13]:
arr3= arr1.ravel()
arr3

array([1, 2, 3, 4, 5, 6])

In [15]:
arr3= arr2.reshape(2,3)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr4= arr2.reshape(3,2)
arr4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr= np.array([1,3,4,2,6,5])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
arr[2:]

array([3, 4, 5, 6])

In [25]:
arr[:3]

array([1, 2, 3])

In [31]:
arr[:5]

array([1, 2, 3, 4, 5])

In [32]:
arr2

array([1, 2, 3, 4, 5, 6])

In [33]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
arr3[1:,:1]

array([[3],
       [5]])