# Module 4: Data Structure Assignment

1.  Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 8,10.

a.  Now in the ‘myList’, append these values: 30,40 

b.  After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [ ]:
myList= [10,20,30,'apple', True, 8,10]
print(type(myList))

<class 'list'>


In [ ]:
new_values= [30,40]
myList.append(new_values)
myList
# myList.pop()

[10, 20, 30, 'apple', True, 8, 10, [30, 40]]

In [ ]:
reversedList= myList.reverse
reversedList

<function list.reverse>

2.  Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.

a.  After that eliminate the ‘text’ value form the dictonary.

b.  Add ‘features’ in the dictonary.

c.  Fetch the ‘data’ element from the dictonary and display it in the output.

In [ ]:
my_Dict={1: 'data', 2:'information',3:'text'}
my_Dict

{1: 'data', 2: 'information', 3: 'text'}

In [ ]:
my_Dict.pop(3)
print(my_Dict)

{1: 'data', 2: 'information'}


In [ ]:
new={3: 'features'}
my_Dict.update(new)
my_Dict

{1: 'data', 2: 'information', 3: 'features'}

In [ ]:
my_Dict[1]

'data'

3.  Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [ ]:
my_tuple=(1,2,3,'apple','mango')
type(my_tuple)

tuple

4.  Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50

a.  Find the minimum value from the numeric_tuple.

b.  Concatenate my_tuple with numeric_tuple and store the result in r1.

c.  Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [ ]:
numeric_tuple=(10,20,30,40,50)
type(numeric_tuple)

tuple

In [ ]:
min(numeric_tuple)

10

In [ ]:
r1= my_tuple+numeric_tuple
print(type(r1))
print(r1)

<class 'tuple'>
(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [ ]:
newdupli= my_tuple*2
newdupli

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')

5.  Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to contains{2,3,7,6,1}        
Perform the below operation:

a.  set1 union set2

b.  set1 intersection set2 

c.  set1 difference set2

In [ ]:
set1,set2= {1,2,3,4,5},{2,3,7,6,1}
print(set1)
print(set2)

{1, 2, 3, 4, 5}
{1, 2, 3, 6, 7}


In [ ]:
from typing import Union
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
set1.intersection(set2)

{1, 2, 3}

In [ ]:
set1.difference(set2)

{4, 5}

In [ ]:
set2.difference(set1)

{6, 7}

# Module 4: Numpy Assignment
1.  Create a 3x3 matrix array with values ranging from 2 to 10.

In [ ]:
import numpy as np
np.matrixlib

<module 'numpy.matrixlib' from '/usr/local/lib/python3.7/dist-packages/numpy/matrixlib/__init__.py'>

In [ ]:
np.matrix([[2,3,4],[5,6,7],[8,9,10]])

matrix([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

2.  Create a numpy array having user input values and convert the integer type to the float type of the elements of the array. 

For instance:

Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [ ]:
a= [1,2,3,4]
print(f'{a}is an original array')
x= np.asfarray(a)
print(f'{x} is a float array')

[1, 2, 3, 4]is an original array
[1. 2. 3. 4.] is a float array


3.  Write a Numpy program to append values to the end of an array. 

For instance:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [ ]:
b=[10,20,30]
new_array= [40,50,60,70,80,90]
b.append(new_array)
print(b)

[10, 20, 30, [40, 50, 60, 70, 80, 90]]


4.  Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.

In [ ]:
c=np.array([10,20,30])
d= np.array([[90,40,10],[20,50,10]])
sumArray = np.add(c,d)
sumArray

array([[100,  60,  40],
       [ 30,  70,  40]])

5.  Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:

a.  Extract the 1st row from the array.

b.  Extract the last element from the array.

In [ ]:
x= np.array([[10,20,30,],[40,50,60],[70,80,90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
x[:1]

array([[10, 20, 30]])

In [ ]:
x[2,2]

90

# Module 4: Numpy Assignment

1.  Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 

[

[5, 5, 5],

[5, 5, 5],

[5, 5, 5]

]

In [ ]:
def solve(row, column, element):
  array1= np.full((row, column), element)
  print(array1)

solve(3,3,5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


2.  Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [ ]:
def addition(x,y,z):
  array1= np.sum([x,y,z])
  print(array1)

x= np.array([1,2,3])
y= np.array([3,4,5])
z= np.array([5,6,7])

addition(x,y,z)

36


3.  Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:

[

[1, 2, 3],

[4, 5, 6],

[7, 8, 9],

]

top_left_sub_matrix (matrix, 2, 2) -> should return:

[

[1, 2]

[4, 5]

]

In [10]:
import numpy as np

def new_arr(mat, row, col):
  arr= mat[:row,:col]
  print(arr)

array= np.arange(1,10,1)
matrix= array.reshape(3,3)  

In [11]:
new_arr(matrix, 2,2)

[[1 2]
 [4 5]]


4.  Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:

[

[1, 2, 3],

[4, 5, 6],

[7, 8, 9],

]

sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)

[

[5, 6]

[8, 9]

]

In [12]:
def new_arr2(mat, row, col):
  arr= mat[row:, col:]
  print(arr)

arr= np.arange(1,10,1)
matrix= arr.reshape(3,3)

In [13]:
new_arr2(matrix, 1,1)

[[5 6]
 [8 9]]


5.  Given a 1D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values: 

[1, 1, 1]

solution(arr) -> should return :

{'mean': 1.0, 'std_dev': 0.0}

In [45]:
def diction():
  dict1= dict(mean= array.mean(), std_dev= np.std(array))
  print(dict1)

array= np.array((1,1,1), dtype= int)

In [46]:
diction()

{'mean': 1.0, 'std_dev': 0.0}
